name: Lotto Job

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"   # כל יום ב-18:00 (UTC)

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Lotto Script
        run: node src/job.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/Lotto.csv
          git commit -m "Auto update lotto results" || echo "No changes"
          git push
